# Data Mining

## Preamble

### Modules

In [1]:
import pandas as pd

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

from utils import load_and_drop_na_data

### Loading Data

In [2]:
df = load_and_drop_na_data("../data/raw/raw.csv")

Raw data: 541909 rows
Removed 5225 duplicates
Clean data: 401604 rows

In [3]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

### Configuration

## Market Basket Analysis

In [14]:
apriori_df = df.dropna(subset=["InvoiceNo", "Description"])

apriori_df["Description"] = apriori_df["Description"].str.strip().str.lower()

transactions = apriori_df.groupby("InvoiceNo")["Description"].apply(list).tolist()

[['white hanging heart t-light holder',
  'white metal lantern',
  'cream cupid hearts coat hanger',
  'knitted union flag hot water bottle',
  'red woolly hottie white heart.',
  'set 7 babushka nesting boxes',
  'glass star frosted t-light holder'],
 ['hand warmer union jack', 'hand warmer red polka dot'],
 ['assorted colour bird ornament',
  "poppy's playhouse bedroom",
  "poppy's playhouse kitchen",
  'feltcraft princess charlotte doll',
  'ivory knitted mug cosy',
  'box of 6 assorted colour teaspoons',
  'box of vintage jigsaw blocks',
  'box of vintage alphabet blocks',
  'home building block word',
  'love building block word',
  'recipe box with metal heart',
  'doormat new england'],
 ['jam making set with jars',
  'red coat rack paris fashion',
  'yellow coat rack paris fashion',
  'blue coat rack paris fashion'],
 ['bath building block word'],
 ['alarm clock bakelike pink',
  'alarm clock bakelike red',
  'alarm clock bakelike green',
  'panda and bunnies sticker sheet',
  'stars gift tape',
  'inflatable political globe',
  'vintage heads and tails card game',
  'set/2 red retrospot tea towels',
  'round snack boxes set of4 woodland',
  'spaceboy lunch box',
  'lunch box i love london',
  'circus parade lunch box',
  'charlotte bag dolly girl design',
  'red toadstool led night light',
  'set 2 tea towels i love london',
  'vintage seaside jigsaw puzzles',
  'mini jigsaw circus parade',
  'mini jigsaw spaceboy',
  'mini paint set vintage',
  'postage'],
 ["paper chain kit 50's christmas"],
 ['hand warmer red polka dot', 'hand warmer union jack'],
 ['white hanging heart t-light holder',
  'white metal lantern',
  'cream cupid hearts coat hanger',
  'edwardian parasol red',
  'retro coffee mugs assorted',
  'save the planet mug',
  'vintage billboard drink me mug',
  'vintage billboard love/hate mug',
  'wood 2 drawer cabinet white finish',
  'wood s/3 cabinet ant white finish',
  'wooden picture frame white finish',
  'wooden frame antique white',
  'knitted union flag hot water bottle',
  'red woolly hottie white heart.',
  'set 7 babushka nesting boxes',
  'glass star frosted t-light holder'],
 ['victorian sewing box large']]

In [ ]:
transactions[:5]

In [13]:
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
apriori_df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

,10 colour spaceboy pen,12 coloured party balloons,12 daisy pegs in wood box,12 egg house painted wood,12 hanging eggs hand painted,12 ivory rose peg place settings,12 message cards with envelopes,12 pencil small tube woodland,12 pencils small tube red retrospot,12 pencils small tube skull,...,zinc star t-light holder,zinc sweetheart soap dish,zinc sweetheart wire letter rack,zinc t-light holder star large,zinc t-light holder stars large,zinc t-light holder stars small,zinc top 2 door wooden shelf,zinc willie winkie candle stick,zinc wire kitchen organiser,zinc wire sweetheart letter tray
count,22190,22190,22190,22190,22190,22190,22190,22190,22190,22190,...,22190,22190,22190,22190,22190,22190,22190,22190,22190,22190
unique,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,21941,22050,22128,22125,22183,22098,22003,21912,21879,21896,...,22189,22171,22111,22040,22188,21950,22179,22001,22178,22170

In [ ]:
apriori_df_encoded.head()

In [10]:
frequent_itemsets = apriori(apriori_df_encoded, min_support=0.05, use_colnames=True)

In [11]:
frequent_itemsets[:5]

Empty DataFrame
Columns: [support, itemsets]
Index: []

In [ ]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)

In [ ]:
rules.head()

## Clustering

## Classification

## Time Series